version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      exclude:
        - "androidx.*"
        - "com.android*"
        - "com.google*"
        - "com.kroegerama*"
        - "org.jetbrains*"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
          - "org.jetbrains.kotlin.*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx*"
      ktor:
        patterns:
          - "io.ktor*"
      android:
        patterns:
          - "com.android*"
      androidx:
        patterns:
          - "androidx.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
